//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTokenQuickBook
    {
        public int AccessTokenQuickbooksID { get; set; }
        public string RealmId { get; set; }
        public string OAuthAccessToken { get; set; }
        public string OAuthAccesTokenSecreet { get; set; }
        public Nullable<int> DataSource { get; set; }
        public string user { get; set; }
    }
}
