//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public long AirportID { get; set; }
        public string AirportName { get; set; }
        public string City { get; set; }
        public string IATA { get; set; }
        public string ICAO { get; set; }
        public string Country { get; set; }
    }
}
