//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNAddress
    {
        public long ASNHierarchicalLevelAddressID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string Name { get; set; }
        public string IdentificationCodeQualifier { get; set; }
        public string IdentificationCode { get; set; }
        public string EntityRelationshipCode { get; set; }
        public string EntityIdentifierCode2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> NumberIdShipmentLevel { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
