//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNCarrierDetailEquipment
    {
        public long CarrierDetailsEquipmentID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string DescriptionCode { get; set; }
        public string EquipmentInitial { get; set; }
        public string EquipmentNo { get; set; }
        public string WeightQualifier { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string UnitMeasurementCode1 { get; set; }
        public string OwnershipCode { get; set; }
        public string SealStatusCode { get; set; }
        public string SealNumber { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<int> NumberIdShipmentLevel { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
