//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNDateTimeReference
    {
        public long DateTimeReferenceID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string Qualifier { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string TimeCode { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
