//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASNItem()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public long ASNItemID { get; set; }
        public long ASNPackageID { get; set; }
        public Nullable<long> POItemID { get; set; }
        public Nullable<long> ProductListID { get; set; }
        public string ItemCode { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string UPC { get; set; }
        public string UPCEAN { get; set; }
        public string ISBN { get; set; }
        public string CaseCode { get; set; }
        public string ShippingContainerCode { get; set; }
        public string BuyerPartNumber { get; set; }
        public string VendorItemNumber { get; set; }
        public string SKU { get; set; }
        public string CancelReasonCode { get; set; }
        public string StatusReasonCode { get; set; }
        public Nullable<System.DateTime> ExpectDeliveryDate { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public string BuyersCatalogue { get; set; }
        public string SerialNumber { get; set; }
        public string BuyersStyleNumber { get; set; }
        public string CancelReferenceCode { get; set; }
    
        public virtual ASNPackage ASNPackage { get; set; }
        public virtual POItem POItem { get; set; }
        public virtual ProductList ProductList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
