//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASNPackage()
        {
            this.ASNItems = new HashSet<ASNItem>();
            this.ASNMarksAndNumbers = new HashSet<ASNMarksAndNumber>();
            this.ASNPackageCarrierDetails = new HashSet<ASNPackageCarrierDetail>();
            this.ASNPackageReferences = new HashSet<ASNPackageReference>();
        }
    
        public long ASNPackageID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string PackageNumber { get; set; }
        public Nullable<short> PackageTypeID { get; set; }
        public long PurchaseOrderID { get; set; }
        public string CarrierTrackingNumber { get; set; }
        public string LotNumber { get; set; }
        public string PalletNumber { get; set; }
        public Nullable<long> LabeledFTID { get; set; }
        public Nullable<int> CartonNumber { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public Nullable<bool> NoLabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNItem> ASNItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNMarksAndNumber> ASNMarksAndNumbers { get; set; }
        public virtual ASNShipment ASNShipment { get; set; }
        public virtual PackageType PackageType { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNPackageCarrierDetail> ASNPackageCarrierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNPackageReference> ASNPackageReferences { get; set; }
    }
}
