//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNPortOrTerminal
    {
        public long ASNPortOrTerminalID { get; set; }
        public long ASNVesselIdentificationID { get; set; }
        public string FunctionCode { get; set; }
        public string LocationQualifier { get; set; }
        public string LocationIdentifier { get; set; }
        public string PortName { get; set; }
        public string CountryCode { get; set; }
        public string TerminalName { get; set; }
        public string PierNumber { get; set; }
        public string StatOrProvince { get; set; }
    
        public virtual ASNVesselIdentification ASNVesselIdentification { get; set; }
    }
}
