//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNPackageCarrierDetail
    {
        public long ASNPackageCarrierDetailID { get; set; }
        public long ASNPackageID { get; set; }
        public string PackagingCode { get; set; }
        public string LadingQuantity { get; set; }
        public string CommodityCodeQualifier { get; set; }
        public string CommodityCode { get; set; }
        public string LadingDescription { get; set; }
        public string WeightQualifier { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string UnitMeasurementCode1 { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string UnitMeasurementCode2 { get; set; }
    
        public virtual ASNPackage ASNPackage { get; set; }
    }
}
