//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNReferenceIdentification
    {
        public long ASNReferenceIdentificationID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string ReferenceType { get; set; }
        public string Qualifier { get; set; }
        public string Value { get; set; }
        public Nullable<int> NumberIdShipmentLevel { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
