//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNShipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASNShipment()
        {
            this.ASNAddresses = new HashSet<ASNAddress>();
            this.ASNAllowanceCharges = new HashSet<ASNAllowanceCharge>();
            this.ASNCarrierDetails = new HashSet<ASNCarrierDetail>();
            this.ASNCarrierDetailEquipments = new HashSet<ASNCarrierDetailEquipment>();
            this.ASNCarrierDetailRoutings = new HashSet<ASNCarrierDetailRouting>();
            this.ASNDateTimeReferences = new HashSet<ASNDateTimeReference>();
            this.ASNPackages = new HashSet<ASNPackage>();
            this.ASNReferenceIdentifications = new HashSet<ASNReferenceIdentification>();
            this.ASNVesselIdentifications = new HashSet<ASNVesselIdentification>();
            this.EventNotificationShips = new HashSet<EventNotificationShip>();
            this.LabelCartonNumbers = new HashSet<LabelCartonNumber>();
            this.SectionShips = new HashSet<SectionShip>();
            this.ZASNLevelPackages = new HashSet<ZASNLevelPackage>();
        }
    
        public long AdvanceShipNoticeID { get; set; }
        public int SourceTradingPartnerID { get; set; }
        public int DestinationTradingPartnerID { get; set; }
        public Nullable<int> BillToAddressID { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string ShipmentIdentification { get; set; }
        public string HierarchicalStructureCode { get; set; }
        public string MethodOfPayment { get; set; }
        public Nullable<int> NumberOfLineItems { get; set; }
        public Nullable<int> HashTotal { get; set; }
        public bool Active { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<int> ServiceLevelID { get; set; }
        public string BOLNumber { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public string DropShipAddress1 { get; set; }
        public string DropShipCity { get; set; }
        public string DropShipSate { get; set; }
        public string DropShipCountry { get; set; }
        public string DropShipPostalCode { get; set; }
        public Nullable<long> Filetransmission { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string InvoiceNumber { get; set; }
        public string CollectID { get; set; }
        public string MasterBOLNumber { get; set; }
        public string LoadNumber { get; set; }
        public string Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNAddress> ASNAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNAllowanceCharge> ASNAllowanceCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNCarrierDetail> ASNCarrierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNCarrierDetailEquipment> ASNCarrierDetailEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNCarrierDetailRouting> ASNCarrierDetailRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNDateTimeReference> ASNDateTimeReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNPackage> ASNPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNReferenceIdentification> ASNReferenceIdentifications { get; set; }
        public virtual Carrier Carrier { get; set; }
        public virtual ServiceLevel ServiceLevel { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress1 { get; set; }
        public virtual FileTransmission FileTransmission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNVesselIdentification> ASNVesselIdentifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventNotificationShip> EventNotificationShips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelCartonNumber> LabelCartonNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionShip> SectionShips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZASNLevelPackage> ZASNLevelPackages { get; set; }
    }
}
