//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNVesselIdentification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASNVesselIdentification()
        {
            this.ASNPortOrTerminals = new HashSet<ASNPortOrTerminal>();
        }
    
        public long ASNVesselIdentificationID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
        public string FlightVoyageNumber { get; set; }
        public string OceanCarrier { get; set; }
        public string RequirementCode { get; set; }
        public string TypeCode { get; set; }
        public string CodeQualifier { get; set; }
        public string TransportationMethod { get; set; }
        public Nullable<int> NumberIdShipmentLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNPortOrTerminal> ASNPortOrTerminals { get; set; }
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
