//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_ElementFormula
    {
        public int ElementFormulaID { get; set; }
        public string Number { get; set; }
        public string Element { get; set; }
        public string Formula { get; set; }
    }
}
