//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_FormField
    {
        public int FieldID { get; set; }
        public int FormID { get; set; }
        public Nullable<int> QualediMappingID { get; set; }
        public string Label { get; set; }
        public int Type { get; set; }
        public Nullable<int> PositionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> ParentField { get; set; }
        public Nullable<int> FieldOrder { get; set; }
        public string Value { get; set; }
        public string ConditionalAction { get; set; }
        public Nullable<int> SpecificIndex { get; set; }
    
        public virtual BB_Form BB_Form { get; set; }
        public virtual BB_QualediMapping BB_QualediMapping { get; set; }
    }
}
