//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_QualediMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_QualediMapping()
        {
            this.BB_FormField = new HashSet<BB_FormField>();
            this.DocumentElements = new HashSet<DocumentElement>();
            this.ValidationRules = new HashSet<ValidationRule>();
        }
    
        public int QualediMappingID { get; set; }
        public int QualediFileID { get; set; }
        public int ElementOrder { get; set; }
        public string Label { get; set; }
        public int ElementLevel { get; set; }
        public string Data { get; set; }
        public string Element { get; set; }
        public string DataElementName { get; set; }
        public string Type { get; set; }
        public string UseType { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_FormField> BB_FormField { get; set; }
        public virtual BB_QualediFile BB_QualediFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentElement> DocumentElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationRule> ValidationRules { get; set; }
    }
}
