//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_QualediFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BB_QualediFile()
        {
            this.BB_Form = new HashSet<BB_Form>();
            this.BB_QualediMapping = new HashSet<BB_QualediMapping>();
        }
    
        public int QualediFileID { get; set; }
        public string Format { get; set; }
        public string Number { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string SchemaFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Form> BB_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_QualediMapping> BB_QualediMapping { get; set; }
    }
}
