//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGWindowsService
    {
        public int BGWindowsServicesID { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string TimerName { get; set; }
        public Nullable<System.DateTime> LastRunService { get; set; }
        public Nullable<System.DateTime> LastRunTimer { get; set; }
    }
}
