//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierShipmentStatu
    {
        public long CarrierShipmentStatusID { get; set; }
        public long CarrierShipment { get; set; }
        public string ShipmentStatusCode { get; set; }
        public string AppointmentReasonCode { get; set; }
        public string AppointmentStatusCode { get; set; }
        public string AppointmentReasonCode_AT704 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string TimeZoneQualifier { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string LongitudeCode { get; set; }
        public string LatitudeCode { get; set; }
        public string EastWestDirectionIdCode { get; set; }
        public string NorthSouthDirectionIdCode { get; set; }
        public string WeightQualifier { get; set; }
        public string WeightUnitCode { get; set; }
        public string Weight { get; set; }
        public string ServiceLevelCode { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string EntityTypeQualifier { get; set; }
        public string OrganizationName { get; set; }
        public string NameFirst { get; set; }
    
        public virtual CarrierShipment CarrierShipment1 { get; set; }
        public virtual CarrierShipmentStatusCode CarrierShipmentStatusCode { get; set; }
    }
}
