//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierShipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrierShipment()
        {
            this.CarrierShipmentStatus = new HashSet<CarrierShipmentStatu>();
        }
    
        public long CarrierShipmentID { get; set; }
        public int ExternalPartner { get; set; }
        public int InternalPartner { get; set; }
        public string ShipmentNumber { get; set; }
        public string SCAC { get; set; }
        public string ReferenceNumber { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<long> FileTransmission { get; set; }
        public Nullable<long> ControlNumber { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<System.DateTime> OriginalDateTime { get; set; }
        public Nullable<long> FTAcknowledgment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierShipmentStatu> CarrierShipmentStatus { get; set; }
        public virtual Hub Hub { get; set; }
        public virtual FileTransmission FileTransmission1 { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual FileTransmission FileTransmission2 { get; set; }
    }
}
