//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentElement()
        {
            this.DocumentElement1 = new HashSet<DocumentElement>();
        }
    
        public long DocumentElementID { get; set; }
        public long DocumentID { get; set; }
        public int QualediMappingID { get; set; }
        public Nullable<long> ParentElement { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Path { get; set; }
    
        public virtual BB_QualediMapping BB_QualediMapping { get; set; }
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentElement> DocumentElement1 { get; set; }
        public virtual DocumentElement DocumentElement2 { get; set; }
    }
}
