//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentAction()
        {
            this.ActionHistories = new HashSet<ActionHistory>();
        }
    
        public long DocumentActionID { get; set; }
        public string DocumentTypeCode { get; set; }
        public int TradingPartnerID { get; set; }
        public string Action { get; set; }
        public Nullable<int> TransmissionChannelID { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<short> Priority { get; set; }
        public string NewStatus { get; set; }
        public Nullable<int> SourceTradingPartnerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionHistory> ActionHistories { get; set; }
        public virtual TransmissionChannel TransmissionChannel { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
    }
}
