//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentType()
        {
            this.DocumentActions = new HashSet<DocumentAction>();
            this.DocumentNotifications = new HashSet<DocumentNotification>();
            this.IncomingDocumentDetails = new HashSet<IncomingDocumentDetail>();
            this.TradingPartnerDocumentTypes = new HashSet<TradingPartnerDocumentType>();
            this.FileTransmissions = new HashSet<FileTransmission>();
            this.HubEDISegments = new HashSet<HubEDISegment>();
            this.Messages = new HashSet<Message>();
            this.MessageActions = new HashSet<MessageAction>();
            this.TradingPartnerFileColumns = new HashSet<TradingPartnerFileColumn>();
        }
    
        public string DocumentTypeCode { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string BillablePattern { get; set; }
        public string IdentityElement { get; set; }
        public string AdditionalElements { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAction> DocumentActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentNotification> DocumentNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingDocumentDetail> IncomingDocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerDocumentType> TradingPartnerDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTransmission> FileTransmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HubEDISegment> HubEDISegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageAction> MessageActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerFileColumn> TradingPartnerFileColumns { get; set; }
    }
}
