//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIFilter
    {
        public byte EDIFilterID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
