//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDILog
    {
        public long EDILogID { get; set; }
        public string ShipFrom { get; set; }
        public string ShipTo { get; set; }
        public string DcumentType { get; set; }
        public long DocumentID { get; set; }
        public string DocuemntStatus { get; set; }
        public string ShippingMethod { get; set; }
        public string ReceprionMethod { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
    }
}
