//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Environment()
        {
            this.Channels = new HashSet<Channel>();
        }
    
        public int EnvironmentID { get; set; }
        public int TradingPartnerID { get; set; }
        public int ProtocolID { get; set; }
        public Nullable<int> Port { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public string FileFormat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Channel> Channels { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
