//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquivalentItem
    {
        public int SourceTradingPartner { get; set; }
        public string SourceItemCode { get; set; }
        public string SourceItemDescription { get; set; }
        public int DestinationTradingPartner { get; set; }
        public string DestinationItemCode { get; set; }
        public string DestinationItemDescription { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
    }
}
