//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventNotificationShip
    {
        public int EventNotificationShipID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string EventNotificationType { get; set; }
        public string MawbHawb { get; set; }
        public string EmailAddress { get; set; }
        public string CellPhoneNumber { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
