//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubEDISegment
    {
        public int HubID { get; set; }
        public string DocumentTypeCode { get; set; }
        public string Segment { get; set; }
        public string AdditionalInfo { get; set; }
        public int ClientTradingPartnerID { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Hub Hub { get; set; }
    }
}
