//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubSpecification
    {
        public int HubSpecificationID { get; set; }
        public int HubID { get; set; }
        public string DocumentType { get; set; }
        public string DocumentURL { get; set; }
    
        public virtual Hub Hub { get; set; }
    }
}
