//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubSetupStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HubSetupStep()
        {
            this.TradingPartnerHubSetupSteps = new HashSet<TradingPartnerHubSetupStep>();
        }
    
        public byte HubSetupID { get; set; }
        public byte StepNumber { get; set; }
        public string StepName { get; set; }
        public string StepDescription { get; set; }
        public Nullable<byte> StepDependence { get; set; }
    
        public virtual HubSetup HubSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerHubSetupStep> TradingPartnerHubSetupSteps { get; set; }
    }
}
