//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncommingEmailAccount
    {
        public long IncommingEmailAccountID { get; set; }
        public string MessageServerID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> TradingPartnerID { get; set; }
        public string EmailSource { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
