//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingDocument()
        {
            this.IncomingDocumentDetails = new HashSet<IncomingDocumentDetail>();
        }
    
        public long IncomingDocumentID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string RemoteFileName { get; set; }
        public Nullable<long> FileTransmission { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public string FunctionalCode { get; set; }
        public string GroupControlNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual FileTransmission FileTransmission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingDocumentDetail> IncomingDocumentDetails { get; set; }
    }
}
