//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngramShipment
    {
        public int IngramShipmentID { get; set; }
        public int TradingPartnerID { get; set; }
        public string FileName { get; set; }
        public string DateShipped { get; set; }
        public string Distributor { get; set; }
        public string PONumber { get; set; }
        public string BackOrder { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumbers { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
