//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTermsOfSale
    {
        public long InvoiceTermsOfSaleID { get; set; }
        public string TermsTypeCode { get; set; }
        public string TermsBasisCode { get; set; }
        public Nullable<decimal> TermsDiscountPercent { get; set; }
        public Nullable<System.DateTime> TermsDiscountDueDate { get; set; }
        public Nullable<int> TermsDiscountDaysDue { get; set; }
        public Nullable<System.DateTime> TermsNetDueDate { get; set; }
        public Nullable<int> TermsNetDays { get; set; }
        public Nullable<int> TermsDayOfMonth { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string Description { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
