//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceCarrierDetail
    {
        public long InvoiceCarrierDetailID { get; set; }
        public string Routing { get; set; }
        public string RefernceIdQualifier { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string ReferenceNumberQualifier { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
