//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceAddresses = new HashSet<InvoiceAddress>();
            this.InvoiceAllowanceOrCharges = new HashSet<InvoiceAllowanceOrCharge>();
            this.InvoiceCarrierDetails = new HashSet<InvoiceCarrierDetail>();
            this.InvoiceDateTimeReferences = new HashSet<InvoiceDateTimeReference>();
            this.InvoiceReferenceIdentifications = new HashSet<InvoiceReferenceIdentification>();
            this.InvoiceShipmentSummaries = new HashSet<InvoiceShipmentSummary>();
            this.InvoiceSummaryTaxInfoes = new HashSet<InvoiceSummaryTaxInfo>();
            this.InvoiceTermsOfSales = new HashSet<InvoiceTermsOfSale>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.POInvoices = new HashSet<POInvoice>();
        }
    
        public long InvoiceID { get; set; }
        public int TradingPartnerID { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string CurrencyCode { get; set; }
        public string MethodOfPayment { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> NumberOfLineItems { get; set; }
        public Nullable<int> HashTotal { get; set; }
        public bool Active { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> BillToAddressID { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public Nullable<long> FiletransmissionID { get; set; }
        public string BOLNumber { get; set; }
    
        public virtual FileTransmission FileTransmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAddress> InvoiceAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAllowanceOrCharge> InvoiceAllowanceOrCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceCarrierDetail> InvoiceCarrierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDateTimeReference> InvoiceDateTimeReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReferenceIdentification> InvoiceReferenceIdentifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceShipmentSummary> InvoiceShipmentSummaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceSummaryTaxInfo> InvoiceSummaryTaxInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTermsOfSale> InvoiceTermsOfSales { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POInvoice> POInvoices { get; set; }
    }
}
