//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSummaryTaxInfo
    {
        public long InvoiceSummaryTaxInfoID { get; set; }
        public string TaxTypeCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public string TaxExemptCode { get; set; }
        public Nullable<decimal> TaxDollarBasisForPercent { get; set; }
        public string TaxIdentificationNumber { get; set; }
        public Nullable<long> InvoiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
