//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceItem()
        {
            this.InvoiceItemPricingInformations = new HashSet<InvoiceItemPricingInformation>();
            this.InvoiceItemTaxInformations = new HashSet<InvoiceItemTaxInformation>();
        }
    
        public long InvoiceItemID { get; set; }
        public long InvoiceID { get; set; }
        public Nullable<long> POItem { get; set; }
        public Nullable<long> ASNItem { get; set; }
        public string DropShipAddress1 { get; set; }
        public string DropShipCity { get; set; }
        public string DropShipState { get; set; }
        public string DropShipCountry { get; set; }
        public string DropShipPostalCode { get; set; }
        public string ItemCode { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string UPC { get; set; }
        public string UPCEAN { get; set; }
        public string ISBN { get; set; }
        public string CaseCode { get; set; }
        public string ShippingContainerCode { get; set; }
        public string BuyerPartNumber { get; set; }
        public string VendorItemNumber { get; set; }
    
        public virtual ASNItem ASNItem1 { get; set; }
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItemPricingInformation> InvoiceItemPricingInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItemTaxInformation> InvoiceItemTaxInformations { get; set; }
        public virtual POItem POItem1 { get; set; }
    }
}
