//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAllowanceTaxInfo
    {
        public long InvAllowanceOrChargeTaxInfoID { get; set; }
        public string TaxTypeCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<long> InvoiceAllowanceOrChargeID { get; set; }
    
        public virtual InvoiceAllowanceOrCharge InvoiceAllowanceOrCharge { get; set; }
    }
}
