//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAllowanceOrCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceAllowanceOrCharge()
        {
            this.InvoiceAllowanceTaxInfoes = new HashSet<InvoiceAllowanceTaxInfo>();
        }
    
        public long InvoiceAllowanceOrChargeID { get; set; }
        public string Indicator { get; set; }
        public string ACCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Description { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string HandlingMethod { get; set; }
        public string IndicatorACCode { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAllowanceTaxInfo> InvoiceAllowanceTaxInfoes { get; set; }
    }
}
