//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemByPass
    {
        public long ItemByPassID { get; set; }
        public int SourceTP { get; set; }
        public int DestTP { get; set; }
        public string ItemCode { get; set; }
        public string UPC { get; set; }
        public string EAN { get; set; }
        public string VendorItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public bool Active { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
    }
}
