//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelCartonNumber
    {
        public long LabelCartonNumberID { get; set; }
        public Nullable<long> WOShipmentPackageID { get; set; }
        public string CartonNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Series { get; set; }
        public Nullable<int> SequentialNumber { get; set; }
        public Nullable<long> AdvanceShipNoticeID { get; set; }
        public Nullable<int> TradingPartnerID { get; set; }
        public Nullable<long> Filetransmission { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual WOShipmentPackage WOShipmentPackage { get; set; }
    }
}
