//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public long LogEntryID { get; set; }
        public string Source { get; set; }
        public string Level { get; set; }
        public string LogEntryTypeCode { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string ActualMessage { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserIP { get; set; }
        public string UserBrowser { get; set; }
        public string UserLanguage { get; set; }
        public string UserResolution { get; set; }
        public string UserOS { get; set; }
        public string AdditionalData { get; set; }
        public Nullable<System.DateTime> AckedDateTime { get; set; }
        public Nullable<int> FileTransmissionID { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual LogEntryType LogEntryType { get; set; }
    }
}
