//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogEntryType()
        {
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public string LogEntryTypeCode { get; set; }
        public string ErrorMessage { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }
        public string MatchPattern1 { get; set; }
        public string MatchPattern2 { get; set; }
        public string Browsers { get; set; }
        public string OperatingSystems { get; set; }
        public Nullable<bool> NotifySupport { get; set; }
        public Nullable<bool> NotifyDevelopment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
