//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAction
    {
        public long MessageActionID { get; set; }
        public string DocumentTypeCode { get; set; }
        public int TradingPartnerID { get; set; }
        public string Action { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<short> Priority { get; set; }
        public string NewStatus { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual PurchaseOrderStatu PurchaseOrderStatu { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
