//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnershipDocumentType
    {
        public int MasterTradingPartnerID { get; set; }
        public int SlaveTradingPartnerID { get; set; }
        public int TradingPartnerDocumentTypeID { get; set; }
        public string ISAVersion { get; set; }
        public string GSVersion { get; set; }
    
        public virtual Partnership Partnership { get; set; }
        public virtual TradingPartnerDocumentType TradingPartnerDocumentType { get; set; }
    }
}
