//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partnership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partnership()
        {
            this.PartnershipDocumentTypes = new HashSet<PartnershipDocumentType>();
        }
    
        public int MasterTradingPartner { get; set; }
        public int SlaveTradingPartner { get; set; }
        public string MasterISAQualifier { get; set; }
        public string MasterISACode { get; set; }
        public string MasterGSQualifier { get; set; }
        public string MasterGSCode { get; set; }
        public string MasterCustomCode { get; set; }
        public string SlaveISAQualifier { get; set; }
        public string SlaveISACode { get; set; }
        public string SlaveGSQualifier { get; set; }
        public string SlaveGSCode { get; set; }
        public string SlaveCustomCode { get; set; }
        public string ShipmentMethodOfPaymentCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> DefaultInputChannel { get; set; }
        public Nullable<int> DefaultOutputChannel { get; set; }
        public Nullable<bool> IsDropShip { get; set; }
        public string UsageIndicator { get; set; }
        public string InvoiceTermsOfSale { get; set; }
        public string LabelTemplate { get; set; }
        public string PackingSlipTemplate { get; set; }
        public string GSAgencyCode { get; set; }
        public string ComponentSeparator { get; set; }
        public string ISAStandardIdentifier { get; set; }
        public Nullable<bool> ISAAckRequired { get; set; }
        public string ISAComponentSeparator { get; set; }
        public Nullable<bool> UseClientDivisionAsHub { get; set; }
        public Nullable<bool> SplitAsnByPO { get; set; }
        public string PONumberMask { get; set; }
        public Nullable<short> WindowStartDays { get; set; }
        public Nullable<short> WindowEndDays { get; set; }
        public string ShipInfoOrderBy { get; set; }
        public Nullable<bool> NoAck { get; set; }
        public Nullable<bool> ConvertCases { get; set; }
        public Nullable<bool> QualediParseEDI { get; set; }
        public string ISAElementSeparator { get; set; }
        public string ISASegmentSeparator { get; set; }
        public Nullable<bool> ControlNumberPerPartnership { get; set; }
        public Nullable<bool> GlobalDocumentNumber { get; set; }
        public Nullable<bool> DoNotSegregate { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string MasterISAAuthorizationInfoQualifier { get; set; }
        public string MasterISAAuthorizationInfo { get; set; }
        public string MasterISASecurityInfoQualifier { get; set; }
        public string MasterISASecurityInfo { get; set; }
        public Nullable<bool> MarkAsSuccessful { get; set; }
        public string WaitDocType { get; set; }
        public Nullable<int> WaitDocTypeMinutes { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnershipDocumentType> PartnershipDocumentTypes { get; set; }
    }
}
