//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POABaseLineItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POABaseLineItem()
        {
            this.POABaseLineItemDescriptions = new HashSet<POABaseLineItemDescription>();
            this.POABaseLineItemNames = new HashSet<POABaseLineItemName>();
            this.POABaseLinePricingInfoes = new HashSet<POABaseLinePricingInfo>();
            this.POALineItemAcknowledgments = new HashSet<POALineItemAcknowledgment>();
        }
    
        public long POABaseLineItemID { get; set; }
        public Nullable<int> LineItemIdentification { get; set; }
        public Nullable<int> QuantityOrdered { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string BasisOfUnitPriceCode { get; set; }
        public string ProdServIdQualifier { get; set; }
        public string ProdServId { get; set; }
        public string ProdServIdQualifier3 { get; set; }
        public string ProdServId3 { get; set; }
        public Nullable<long> POAcknowledgmentID { get; set; }
        public string ProdServIdQualifier2 { get; set; }
        public string ProdServId2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POABaseLineItemDescription> POABaseLineItemDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POABaseLineItemName> POABaseLineItemNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POABaseLinePricingInfo> POABaseLinePricingInfoes { get; set; }
        public virtual POAcknowledgment POAcknowledgment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POALineItemAcknowledgment> POALineItemAcknowledgments { get; set; }
    }
}
