//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POABaseLineItemName
    {
        public long POABaseLineItemNameID { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string Name { get; set; }
        public Nullable<long> POABaseLineItemID { get; set; }
    
        public virtual POABaseLineItem POABaseLineItem { get; set; }
    }
}
