//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POABaseLinePricingInfo
    {
        public long POABaseLinePricingInfoID { get; set; }
        public string ClassOfTradeCode { get; set; }
        public string PriceQuailifie { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Unit { get; set; }
        public string PriceMultiplierQualifier { get; set; }
        public Nullable<decimal> DiscountMultiplier { get; set; }
        public Nullable<long> POABaseLineItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual POABaseLineItem POABaseLineItem { get; set; }
    }
}
