//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POAcknowledgment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POAcknowledgment()
        {
            this.POAAddresses = new HashSet<POAAddress>();
            this.POAAddressReferences = new HashSet<POAAddressReference>();
            this.POABaseLineItems = new HashSet<POABaseLineItem>();
            this.POADateTimeReferences = new HashSet<POADateTimeReference>();
        }
    
        public long POAcknowledgmentID { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string AckType { get; set; }
        public string SellersOrderNumber { get; set; }
        public Nullable<int> NumberOfLineItems { get; set; }
        public Nullable<int> TotalOrdered { get; set; }
        public long PurchaseOrderID { get; set; }
        public bool Active { get; set; }
        public long FileTransmissionID { get; set; }
    
        public virtual FileTransmission FileTransmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAAddress> POAAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAAddressReference> POAAddressReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POABaseLineItem> POABaseLineItems { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POADateTimeReference> POADateTimeReferences { get; set; }
    }
}
