//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POAddressReference
    {
        public long POAddressReferenceID { get; set; }
        public Nullable<long> POAddressID { get; set; }
        public string ReferenceQualifier { get; set; }
        public string ReferenceIdentification { get; set; }
        public string Description { get; set; }
        public string ReferenceIdentifier { get; set; }
    
        public virtual POAddress POAddress { get; set; }
    }
}
