//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POAddress()
        {
            this.POAddressReferences = new HashSet<POAddressReference>();
            this.POCommunicationContacts = new HashSet<POCommunicationContact>();
        }
    
        public long POAddressID { get; set; }
        public long PurchaseOrderID { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string Name { get; set; }
        public string IdentificationCodeQualifier { get; set; }
        public string IdentificationCode { get; set; }
        public string EntityRelationshipCode { get; set; }
        public string EntityIdentifierCode2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string ReferenceIdQualifier { get; set; }
        public string ReferenceIdentification { get; set; }
        public string ManufactureID { get; set; }
        public string AdditionalName1 { get; set; }
        public string AdditionalName2 { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAddressReference> POAddressReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POCommunicationContact> POCommunicationContacts { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
