//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POALineItemAcknowledgment
    {
        public long POALineItemAcknowledgmentID { get; set; }
        public string LineItemStatusCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public string LineItemDateTimeQualifier { get; set; }
        public Nullable<System.DateTime> LineItemDate { get; set; }
        public string ProdServQualifier { get; set; }
        public string ProdServID { get; set; }
        public string ProdServQualifier2 { get; set; }
        public string ProdServID2 { get; set; }
        public string ProdServQualifier3 { get; set; }
        public string ProdServID3 { get; set; }
        public string ProdServQualifier4 { get; set; }
        public string ProdServID4 { get; set; }
        public string DateTimeQualifier { get; set; }
        public Nullable<System.DateTime> DateTimeDate { get; set; }
        public Nullable<long> POABaseLineItemID { get; set; }
        public Nullable<long> FileTransmissionID { get; set; }
    
        public virtual FileTransmission FileTransmission { get; set; }
        public virtual POABaseLineItem POABaseLineItem { get; set; }
    }
}
