//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POCommunicationContact
    {
        public long POCommunicationsContactID { get; set; }
        public long POAddressID { get; set; }
        public string ContactFunctionCode { get; set; }
        public string Name { get; set; }
        public string CommuNumberQualifier1 { get; set; }
        public string CommuNumber1 { get; set; }
        public string CommuNumberQualifier2 { get; set; }
        public string CommuNumber2 { get; set; }
        public string CommuNumberQualifier3 { get; set; }
        public string CommuNumber3 { get; set; }
        public string ContactInquiryReference { get; set; }
    
        public virtual POAddress POAddress { get; set; }
    }
}
