//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODateTimeReference
    {
        public long PODateTimeReferenceID { get; set; }
        public long PurchaseOrderID { get; set; }
        public string Qualifier { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
