//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POInvoice
    {
        public long POInvoiceID { get; set; }
        public long PurchaseOrderID { get; set; }
        public long InvoiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
