//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POItemDate
    {
        public int POItemDateID { get; set; }
        public long POItemID { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public string DateType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LineItem { get; set; }
    
        public virtual POItem POItem { get; set; }
    }
}
