//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POItemAddress
    {
        public long POItemID { get; set; }
        public int TradingPartnerAddressID { get; set; }
        public int Quantity { get; set; }
    
        public virtual POItem POItem { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress { get; set; }
    }
}
