//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPackage
    {
        public long POPackageID { get; set; }
        public long PurchaseOrderID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string UnitsLength { get; set; }
        public string UnitsWeight { get; set; }
        public string IncoTerm { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
