//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POReferenceText
    {
        public long POReferenceTextID { get; set; }
        public long POExtendedReferenceInfoID { get; set; }
        public string NoteReferenceCode { get; set; }
        public string MessageText { get; set; }
    
        public virtual POExtendedReferenceInfo POExtendedReferenceInfo { get; set; }
    }
}
