//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingQueue
    {
        public int ProcessingQueueID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ServerNumber { get; set; }
        public Nullable<int> FilesPerRound { get; set; }
        public Nullable<int> IntervalSeconds { get; set; }
    }
}
