//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductList()
        {
            this.ASNItems = new HashSet<ASNItem>();
            this.WOSAItems = new HashSet<WOSAItem>();
        }
    
        public long ProductListID { get; set; }
        public int TradingPartnerID { get; set; }
        public string ItemCode { get; set; }
        public string UPC { get; set; }
        public string EAN { get; set; }
        public string ItemDescription { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
        public string ISBN { get; set; }
        public string CaseCode { get; set; }
        public string ShippingContainerCode { get; set; }
        public string BuyerPartNumber { get; set; }
        public string VendorItemNumber { get; set; }
        public string SKU { get; set; }
        public Nullable<int> CasePack { get; set; }
        public string BuyersCatalogue { get; set; }
        public Nullable<int> GrossWeightPerPack { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNItem> ASNItems { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOSAItem> WOSAItems { get; set; }
    }
}
