//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.BookingEvents = new HashSet<BookingEvent>();
            this.BookingEvents1 = new HashSet<BookingEvent>();
            this.BookingItemTrackings = new HashSet<BookingItemTracking>();
            this.ProviderServiceAreas = new HashSet<ProviderServiceArea>();
            this.ProviderServiceTypes = new HashSet<ProviderServiceType>();
        }
    
        public int ProviderID { get; set; }
        public int TradingPartnerID { get; set; }
        public string TaxID { get; set; }
        public string DefaultCurrencyCode { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingEvent> BookingEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingEvent> BookingEvents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingItemTracking> BookingItemTrackings { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderServiceArea> ProviderServiceAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderServiceType> ProviderServiceTypes { get; set; }
    }
}
