//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.ASNCarrierDetails = new HashSet<ASNCarrierDetail>();
            this.ASNPackages = new HashSet<ASNPackage>();
            this.Messages = new HashSet<Message>();
            this.POAcknowledgments = new HashSet<POAcknowledgment>();
            this.POAddresses = new HashSet<POAddress>();
            this.POAllowanceCharges = new HashSet<POAllowanceCharge>();
            this.POCarrierDetails = new HashSet<POCarrierDetail>();
            this.PODateTimeReferences = new HashSet<PODateTimeReference>();
            this.POExtendedReferenceInfoes = new HashSet<POExtendedReferenceInfo>();
            this.POInvoices = new HashSet<POInvoice>();
            this.POItems = new HashSet<POItem>();
            this.POMarkingPackagingLoadings = new HashSet<POMarkingPackagingLoading>();
            this.POPackages = new HashSet<POPackage>();
            this.POProductItemDescriptions = new HashSet<POProductItemDescription>();
            this.POReferenceIdentifications = new HashSet<POReferenceIdentification>();
            this.PORelatedInstructions = new HashSet<PORelatedInstruction>();
            this.POSaleRequirements = new HashSet<POSaleRequirement>();
            this.POSubItems = new HashSet<POSubItem>();
            this.POTermsDiscounts = new HashSet<POTermsDiscount>();
            this.POTransactionTotals = new HashSet<POTransactionTotal>();
            this.RRShipmentInfoOrderDetails = new HashSet<RRShipmentInfoOrderDetail>();
            this.WarehouseOrders = new HashSet<WarehouseOrder>();
        }
    
        public long PurchaseOrderID { get; set; }
        public int HubID { get; set; }
        public int TradingPartnerID { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string TypeCode { get; set; }
        public string Number { get; set; }
        public string RelaseNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string CurrencyCode { get; set; }
        public string ContactFunctionCode { get; set; }
        public string Name { get; set; }
        public string CommunicationNumberQualifier1 { get; set; }
        public string CommunicationNumber1 { get; set; }
        public string CommunicationNumberQualifier2 { get; set; }
        public string CommunicationNumber2 { get; set; }
        public string CommunicationNumberQualifier3 { get; set; }
        public string CommunicationNumber3 { get; set; }
        public string ContactInquiryReference { get; set; }
        public string PurchaseOrderStatusCode { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<decimal> POAmount { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<long> FileTransmissionID { get; set; }
        public Nullable<bool> IsMultistore { get; set; }
        public string TransactionSetControlNumber { get; set; }
        public Nullable<int> IncludedSegmentsNo { get; set; }
        public Nullable<System.DateTime> NotDeliverAfter { get; set; }
        public Nullable<System.DateTime> NotDeliverBefore { get; set; }
        public string Message { get; set; }
        public string WeightUnit { get; set; }
        public string WeightPO { get; set; }
        public string VolumePO { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> LastResetDateTime { get; set; }
        public string RevisionNumber { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<int> Version { get; set; }
        public string SecurityLevelCode { get; set; }
        public Nullable<System.DateTime> DeliveryRequested { get; set; }
        public Nullable<System.DateTime> ShipNoLater { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<System.DateTime> CreationDateBooking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNCarrierDetail> ASNCarrierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNPackage> ASNPackages { get; set; }
        public virtual FileTransmission FileTransmission { get; set; }
        public virtual HubTradingPartner HubTradingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAcknowledgment> POAcknowledgments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAddress> POAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POAllowanceCharge> POAllowanceCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POCarrierDetail> POCarrierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODateTimeReference> PODateTimeReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POExtendedReferenceInfo> POExtendedReferenceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POInvoice> POInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POItem> POItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POMarkingPackagingLoading> POMarkingPackagingLoadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POPackage> POPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POProductItemDescription> POProductItemDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POReferenceIdentification> POReferenceIdentifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORelatedInstruction> PORelatedInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSaleRequirement> POSaleRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSubItem> POSubItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTermsDiscount> POTermsDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTransactionTotal> POTransactionTotals { get; set; }
        public virtual PurchaseOrderStatu PurchaseOrderStatu { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRShipmentInfoOrderDetail> RRShipmentInfoOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOrder> WarehouseOrders { get; set; }
    }
}
