//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBInvoiceItem
    {
        public int QBInvoiceItemID { get; set; }
        public Nullable<int> QBInvoiceID { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual QBInvoice QBInvoice { get; set; }
    }
}
