//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public int ResetPasswordRequestID { get; set; }
        public string Email { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> TimeDuration { get; set; }
        public string Status { get; set; }
    }
}
