//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutingRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoutingRequest()
        {
            this.RoutingRequestAddresses = new HashSet<RoutingRequestAddress>();
            this.RoutingRequestShipmentInfoes = new HashSet<RoutingRequestShipmentInfo>();
        }
    
        public long RoutingRequestID { get; set; }
        public int SourceTP { get; set; }
        public int DestTP { get; set; }
        public Nullable<long> FileTransmissionID { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string RoutingIdentification { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string ShipmentIdentification { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual FileTransmission FileTransmission { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutingRequestAddress> RoutingRequestAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutingRequestShipmentInfo> RoutingRequestShipmentInfoes { get; set; }
    }
}
