//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRShipmentInfoOrderDetail
    {
        public long RRShipmentInfoOrderDetailID { get; set; }
        public long RoutingRequestShipmentInfoID { get; set; }
        public string PONumber { get; set; }
        public long PurchaseOrderID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string QuantityCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightCode { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string VolumeCode { get; set; }
        public string Commodity { get; set; }
        public string ClassificationCode { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual RoutingRequestShipmentInfo RoutingRequestShipmentInfo { get; set; }
    }
}
