//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionShip
    {
        public int SectionShipID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string AcctID { get; set; }
        public string SenderID { get; set; }
        public string MessageID { get; set; }
        public string DocType { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
    }
}
