//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int TaskHistoryID { get; set; }
        public int TaskID { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public byte ScheduledTime { get; set; }
        public System.DateTime ExecutedDateTime { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> TransmissionChannelID { get; set; }
        public Nullable<byte> ScheduledMinutes { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
