//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskHistories = new HashSet<TaskHistory>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public int SourceTP { get; set; }
        public Nullable<int> DestTP { get; set; }
        public string Description { get; set; }
        public bool RunsOnWeekdays { get; set; }
        public bool RunsOnWeekends { get; set; }
        public string RunsOnCustomDays { get; set; }
        public string RunsOnTimes { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> TransmissionChannelID { get; set; }
    
        public virtual TransmissionChannel TransmissionChannel { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskHistory> TaskHistories { get; set; }
    }
}
