//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextMessage
    {
        public int TextMessageID { get; set; }
        public int SourceTradingPartner { get; set; }
        public int DestinationTradingPartner { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }
        public string ReferenceNumber { get; set; }
        public string MessageText { get; set; }
        public Nullable<long> FiletransmissionID { get; set; }
    
        public virtual FileTransmission FileTransmission { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
    }
}
