//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartnerFileColumn
    {
        public long TradingPartnerFileColumnID { get; set; }
        public Nullable<int> TradingPartnerID { get; set; }
        public string DocumentTypeCode { get; set; }
        public string ColumnName { get; set; }
        public string ColumnField { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool Active { get; set; }
        public string Identifier { get; set; }
        public string MasterTradingPartnerID { get; set; }
        public string RuleValue { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
