//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartnerDocumentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TradingPartnerDocumentType()
        {
            this.PartnershipDocumentChannels = new HashSet<PartnershipDocumentChannel>();
            this.PartnershipDocumentTypes = new HashSet<PartnershipDocumentType>();
        }
    
        public int TradingPartnerDocumentTypeID { get; set; }
        public Nullable<int> TradingPartnerID { get; set; }
        public string DocumentTypeCode { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public string ISAVersion { get; set; }
        public string GSVersion { get; set; }
        public string GSIndentifierCode { get; set; }
        public string MasterGSCode { get; set; }
        public string MasterISACode { get; set; }
        public string SlaveGSCode { get; set; }
        public string SlaveISACode { get; set; }
        public Nullable<bool> IsHub { get; set; }
        public string MasterISAQualifier { get; set; }
        public string SlaveISAQualifier { get; set; }
        public string AdditionalInfo { get; set; }
        public string MasterISAAuthorizationInfoQualifier { get; set; }
        public string MasterISAAuthorizationInfo { get; set; }
        public string MasterISASecurityInfoQualifier { get; set; }
        public string MasterISASecurityInfo { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnershipDocumentChannel> PartnershipDocumentChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnershipDocumentType> PartnershipDocumentTypes { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
