//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartnerCarrierAlia
    {
        public int TradingPartnerCarrierAliasID { get; set; }
        public Nullable<int> TradingPartnerID { get; set; }
        public string AliasCode { get; set; }
        public string AliasName { get; set; }
        public Nullable<int> CarrierID { get; set; }
    }
}
