//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TradingPartner()
        {
            this.ASNShipments = new HashSet<ASNShipment>();
            this.ASNShipments1 = new HashSet<ASNShipment>();
            this.BB_Form = new HashSet<BB_Form>();
            this.BB_Form1 = new HashSet<BB_Form>();
            this.CarrierAlias = new HashSet<CarrierAlia>();
            this.CarrierShipments = new HashSet<CarrierShipment>();
            this.Channels = new HashSet<Channel>();
            this.Clients = new HashSet<Client>();
            this.CodeTranslates = new HashSet<CodeTranslate>();
            this.Contacts = new HashSet<Contact>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.DocumentActions = new HashSet<DocumentAction>();
            this.DocumentActions1 = new HashSet<DocumentAction>();
            this.DocumentNotifications = new HashSet<DocumentNotification>();
            this.DocumentNotifications1 = new HashSet<DocumentNotification>();
            this.Environments = new HashSet<Environment>();
            this.EquivalentItems = new HashSet<EquivalentItem>();
            this.EquivalentItems1 = new HashSet<EquivalentItem>();
            this.FileTransmissions = new HashSet<FileTransmission>();
            this.FileTransmissions1 = new HashSet<FileTransmission>();
            this.FileTransmissions2 = new HashSet<FileTransmission>();
            this.FTPSetups = new HashSet<FTPSetup>();
            this.FTPSetups1 = new HashSet<FTPSetup>();
            this.Hubs = new HashSet<Hub>();
            this.HubTradingPartners = new HashSet<HubTradingPartner>();
            this.IncommingEmailAccounts = new HashSet<IncommingEmailAccount>();
            this.IngramShipments = new HashSet<IngramShipment>();
            this.Invoices = new HashSet<Invoice>();
            this.ItemByPasses = new HashSet<ItemByPass>();
            this.ItemByPasses1 = new HashSet<ItemByPass>();
            this.LabelCartonNumbers = new HashSet<LabelCartonNumber>();
            this.MailTemplates = new HashSet<MailTemplate>();
            this.MailTemplates1 = new HashSet<MailTemplate>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.MessageActions = new HashSet<MessageAction>();
            this.Partnerships = new HashSet<Partnership>();
            this.Partnerships1 = new HashSet<Partnership>();
            this.PartnershipDocumentChannels = new HashSet<PartnershipDocumentChannel>();
            this.PartnershipDocumentChannels1 = new HashSet<PartnershipDocumentChannel>();
            this.ProductLists = new HashSet<ProductList>();
            this.Providers = new HashSet<Provider>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.RoutingRequests = new HashSet<RoutingRequest>();
            this.RoutingRequests1 = new HashSet<RoutingRequest>();
            this.Shippers = new HashSet<Shipper>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.TextMessages = new HashSet<TextMessage>();
            this.TextMessages1 = new HashSet<TextMessage>();
            this.TradingPartnerContacts = new HashSet<TradingPartnerContact>();
            this.TradingPartnerHubSetupSteps = new HashSet<TradingPartnerHubSetupStep>();
            this.TradingPartnerLabelColumns = new HashSet<TradingPartnerLabelColumn>();
            this.TradingPartnerDocumentTypes = new HashSet<TradingPartnerDocumentType>();
            this.TradingPartnerDivisions = new HashSet<TradingPartnerDivision>();
            this.TradingPartnerFileColumns = new HashSet<TradingPartnerFileColumn>();
            this.TradingPartnerServiceLevels = new HashSet<TradingPartnerServiceLevel>();
            this.TransmissionChannels = new HashSet<TransmissionChannel>();
            this.TransmissionChannels1 = new HashSet<TransmissionChannel>();
            this.Users = new HashSet<User>();
            this.UserTradingPartners = new HashSet<UserTradingPartner>();
            this.WarehouseOrders = new HashSet<WarehouseOrder>();
            this.WOShipments = new HashSet<WOShipment>();
            this.WOShipments1 = new HashSet<WOShipment>();
        }
    
        public int TradingPartnerID { get; set; }
        public string TradingPartnerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Url { get; set; }
        public string Country { get; set; }
        public bool Active { get; set; }
        public string Vertical { get; set; }
        public string Code { get; set; }
        public Nullable<bool> AddUnknownAddresses { get; set; }
        public string TestCode { get; set; }
        public Nullable<int> QBClientID { get; set; }
        public Nullable<bool> AddUnknownItem { get; set; }
        public string DUNSNumber { get; set; }
        public string UCCNumber { get; set; }
        public Nullable<bool> Qualedi { get; set; }
        public Nullable<int> GMT { get; set; }
        public Nullable<bool> DST { get; set; }
        public Nullable<bool> QualediSingleLine { get; set; }
        public Nullable<bool> QualediNoDescription { get; set; }
        public string DefaultISACode { get; set; }
        public string DefaultISAQualifier { get; set; }
        public string DefaultGSCode { get; set; }
        public Nullable<short> RetransmissionHours { get; set; }
        public Nullable<int> ParentTradingPartnerID { get; set; }
        public string TarePrefix { get; set; }
        public string AuthorizationToken { get; set; }
        public Nullable<short> FulfillmentAlertOffset { get; set; }
        public string DefaultEmailList { get; set; }
        public Nullable<bool> QualediUseHeader { get; set; }
        public Nullable<bool> QualediRepeatHeader { get; set; }
        public Nullable<bool> QualediIncludeDate { get; set; }
        public Nullable<bool> QualediBlankFill { get; set; }
        public string QualediDateFormat { get; set; }
        public Nullable<int> QualediRecordLength { get; set; }
        public string QualediBeginRecord { get; set; }
        public Nullable<bool> QualediTerminateCR { get; set; }
        public Nullable<bool> QualediTerminateLF { get; set; }
        public Nullable<bool> QualediTerminateFS { get; set; }
        public Nullable<bool> QualediTerminateGS { get; set; }
        public Nullable<bool> QualediSortSeg { get; set; }
        public Nullable<bool> AllowSendEDIFromPortal { get; set; }
        public string TemplatePDF { get; set; }
        public Nullable<bool> MenuMixedMode { get; set; }
        public string PortalOptions { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> QueueID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNShipment> ASNShipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNShipment> ASNShipments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Form> BB_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BB_Form> BB_Form1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierAlia> CarrierAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrierShipment> CarrierShipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Channel> Channels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeTranslate> CodeTranslates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAction> DocumentActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAction> DocumentActions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentNotification> DocumentNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentNotification> DocumentNotifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Environment> Environments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquivalentItem> EquivalentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquivalentItem> EquivalentItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTransmission> FileTransmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTransmission> FileTransmissions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTransmission> FileTransmissions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTPSetup> FTPSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTPSetup> FTPSetups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hub> Hubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HubTradingPartner> HubTradingPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncommingEmailAccount> IncommingEmailAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngramShipment> IngramShipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemByPass> ItemByPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemByPass> ItemByPasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelCartonNumber> LabelCartonNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailTemplate> MailTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailTemplate> MailTemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageAction> MessageActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partnership> Partnerships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partnership> Partnerships1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnershipDocumentChannel> PartnershipDocumentChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnershipDocumentChannel> PartnershipDocumentChannels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductList> ProductLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual QBClient QBClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutingRequest> RoutingRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutingRequest> RoutingRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipper> Shippers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextMessage> TextMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextMessage> TextMessages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerContact> TradingPartnerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerHubSetupStep> TradingPartnerHubSetupSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerLabelColumn> TradingPartnerLabelColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerDocumentType> TradingPartnerDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerDivision> TradingPartnerDivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerFileColumn> TradingPartnerFileColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingPartnerServiceLevel> TradingPartnerServiceLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransmissionChannel> TransmissionChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransmissionChannel> TransmissionChannels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTradingPartner> UserTradingPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOrder> WarehouseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOShipment> WOShipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOShipment> WOShipments1 { get; set; }
    }
}
