//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartnerHubSetupStep
    {
        public int TradingPartnerID { get; set; }
        public byte HubSetupID { get; set; }
        public byte StepNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    
        public virtual HubSetupStep HubSetupStep { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
    }
}
