//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmissionChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransmissionChannel()
        {
            this.ActionHistories = new HashSet<ActionHistory>();
            this.ContactChannels = new HashSet<ContactChannel>();
            this.DocumentActions = new HashSet<DocumentAction>();
            this.FileTransmissions = new HashSet<FileTransmission>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int TransmissionChannelID { get; set; }
        public string Name { get; set; }
        public string ChannelType { get; set; }
        public Nullable<int> SourceTradingPartnerID { get; set; }
        public Nullable<int> DestTradingPartnerID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Port { get; set; }
        public string Url { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public string AdditionalInfo { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> MustRead { get; set; }
        public Nullable<bool> CanWrite { get; set; }
        public Nullable<bool> MustDelete { get; set; }
        public string NameFilter { get; set; }
        public string ContentFilter { get; set; }
        public string StatusInfo { get; set; }
        public Nullable<bool> SigleCopy { get; set; }
        public string VanName { get; set; }
        public Nullable<int> OwnerTP { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> ProcessingQueueID { get; set; }
        public Nullable<int> IntervalMinutes { get; set; }
        public Nullable<int> ServerNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionHistory> ActionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactChannel> ContactChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAction> DocumentActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTransmission> FileTransmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual TradingPartner TradingPartner1 { get; set; }
    }
}
