//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnAroundDocument
    {
        public int TurnAroundDocumentID { get; set; }
        public string InputDocument { get; set; }
        public string OutputDocument { get; set; }
    }
}
