//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOperation
    {
        public long UserOperationID { get; set; }
        public long UserID { get; set; }
        public System.DateTime OperationDateTime { get; set; }
        public string RequestMethod { get; set; }
        public string RequestUri { get; set; }
        public string RequestContent { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
    
        public virtual User User { get; set; }
    }
}
