//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTradingPartner
    {
        public int UserTradingPartnerID { get; set; }
        public long UserID { get; set; }
        public int TradingPartnerID { get; set; }
        public string Permissions { get; set; }
    
        public virtual TradingPartner TradingPartner { get; set; }
        public virtual User User { get; set; }
    }
}
