//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationRule
    {
        public int ValidationRuleID { get; set; }
        public Nullable<int> SourceTP { get; set; }
        public Nullable<int> DestTP { get; set; }
        public int QualediMappingID { get; set; }
        public string RuleName { get; set; }
        public Nullable<int> LinkQualediMappingID { get; set; }
        public string LinkValue { get; set; }
        public string RuleValue { get; set; }
    
        public virtual BB_QualediMapping BB_QualediMapping { get; set; }
    }
}
