//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOReferenceIdentification
    {
        public long RefernceIdentificationID { get; set; }
        public string CustomerNumber { get; set; }
        public long WarehouseOrderID { get; set; }
        public string WarehouseLocation { get; set; }
        public string SupplierNumber { get; set; }
        public string PurchaseOrderSuffix { get; set; }
        public string DespartmentNumber { get; set; }
        public string MasterCarton { get; set; }
        public Nullable<long> WOShipmentID { get; set; }
    
        public virtual WarehouseOrder WarehouseOrder { get; set; }
        public virtual WOShipment WOShipment { get; set; }
    }
}
