//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOSAPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WOSAPackage()
        {
            this.WOSAItems = new HashSet<WOSAItem>();
        }
    
        public long WOSAPackageID { get; set; }
        public long WOShippingAdviceID { get; set; }
        public string PackageNumber { get; set; }
        public string CartonType { get; set; }
        public string ManifestNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOSAItem> WOSAItems { get; set; }
        public virtual WOShippingAdvice WOShippingAdvice { get; set; }
    }
}
