//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOSAItem
    {
        public long WOSAItemID { get; set; }
        public long WOSAPackageID { get; set; }
        public Nullable<long> WOShipmentItemID { get; set; }
        public Nullable<long> ProductListID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> QuantityShipped { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string UPC { get; set; }
        public string DeliveryNumber { get; set; }
    
        public virtual ProductList ProductList { get; set; }
        public virtual WOSAPackage WOSAPackage { get; set; }
        public virtual WOShipmentItem WOShipmentItem { get; set; }
    }
}
