//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOShipmentItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WOShipmentItem()
        {
            this.WOSAItems = new HashSet<WOSAItem>();
            this.WOShipmentItemReferenceIds = new HashSet<WOShipmentItemReferenceId>();
        }
    
        public long WOShipmentItemID { get; set; }
        public long WOShipmentPackageID { get; set; }
        public Nullable<long> ProductListID { get; set; }
        public string LineItem { get; set; }
        public Nullable<long> QuantityOrdered { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PriceCode { get; set; }
        public string ItemNumber { get; set; }
        public string Sku { get; set; }
        public string CarryOverPartNumber { get; set; }
        public string ModelNumber { get; set; }
        public string ManufcPartNumber { get; set; }
        public string BuyersCatalogue { get; set; }
        public string BuyersPartNumber { get; set; }
        public string Upc { get; set; }
        public string UpcEan { get; set; }
        public string VendorsPartNumber { get; set; }
        public string ItemCode { get; set; }
        public string VendorsItemNumber { get; set; }
        public string VendorsCatalogue { get; set; }
        public string VendorsStyleNumber { get; set; }
        public string ItemDescriptionType { get; set; }
        public string ProductCharacterCode { get; set; }
        public string AgencyQualifierCode { get; set; }
        public string ProductDescriptionCode { get; set; }
        public string ItemDescription { get; set; }
        public string MessageText { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasure { get; set; }
        public string VendorColorDescription { get; set; }
        public string VendorSizeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOSAItem> WOSAItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOShipmentItemReferenceId> WOShipmentItemReferenceIds { get; set; }
        public virtual WOShipmentPackage WOShipmentPackage { get; set; }
    }
}
