//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOShippingAdvice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WOShippingAdvice()
        {
            this.WOSAPackages = new HashSet<WOSAPackage>();
        }
    
        public long WOShippingAdviceID { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<int> ShipToAddress { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string MethodOfPayment { get; set; }
        public string TrackingNumber { get; set; }
        public bool Active { get; set; }
        public Nullable<long> WOShipmentID { get; set; }
        public Nullable<long> FileTransmissionID { get; set; }
        public Nullable<long> ControlNumber { get; set; }
        public Nullable<long> GroupControlNumber { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual FileTransmission FileTransmission { get; set; }
        public virtual TradingPartnerAddress TradingPartnerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOSAPackage> WOSAPackages { get; set; }
        public virtual WOShipment WOShipment { get; set; }
    }
}
