//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZASNLevelItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZASNLevelItem()
        {
            this.ASNReferenceIdentificationLevelItems = new HashSet<ASNReferenceIdentificationLevelItem>();
        }
    
        public long ASNLevelItemID { get; set; }
        public long ASNLevelPackageID { get; set; }
        public string IdentificationNo { get; set; }
        public string ParentIdNumber { get; set; }
        public string LevelCode { get; set; }
        public string ChildCode { get; set; }
        public string ItemIdentification { get; set; }
        public string Qualifier { get; set; }
        public string ItemNumber { get; set; }
        public string Qualifier2 { get; set; }
        public string ItemNumber2 { get; set; }
        public string ShipNoticeItemIdentification { get; set; }
        public Nullable<int> UnitsShipped { get; set; }
        public string UnitMeasurementCode { get; set; }
        public string ItemDescriptionType { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASNReferenceIdentificationLevelItem> ASNReferenceIdentificationLevelItems { get; set; }
        public virtual ZASNLevelPackage ZASNLevelPackage { get; set; }
    }
}
