//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZASNLevelPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZASNLevelPackage()
        {
            this.ZASNLevelItems = new HashSet<ZASNLevelItem>();
        }
    
        public long ASNLevelPackageID { get; set; }
        public long AdvanceShipNoticeID { get; set; }
        public string IdentificationNo { get; set; }
        public string ParentIdNumber { get; set; }
        public string LevelCode { get; set; }
        public string ChildCode { get; set; }
    
        public virtual ASNShipment ASNShipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZASNLevelItem> ZASNLevelItems { get; set; }
    }
}
