//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServicesHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zInvoiceItem
    {
        public long InvoiceItemID { get; set; }
        public Nullable<int> ItemIdentification { get; set; }
        public Nullable<int> QuantityInvoiced { get; set; }
        public string BaisOfUnitPriceCode { get; set; }
        public string ProdServIdQualifier { get; set; }
        public string ProdServID { get; set; }
        public string ProdServIdQualifier2 { get; set; }
        public string ProdServID2 { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string ProductDescriptionType { get; set; }
        public string ProductDescription { get; set; }
        public string EntityIDentifierCode { get; set; }
        public string Name { get; set; }
    }
}
